sudo: false
language: python
install:
  - pip install ansible jenkins-job-builder
script:
  - ansible-playbook --syntax-check ci/ansible/*.yaml
  - jenkins-jobs --conf ci/jobs/jenkins_jobs.ini.example test -r -o /tmp/jobs ci/jobs
