# Define what action to perform
#
# Possible values are:
#  * install: to install the coverage hook
#  * report: to generate the coverage report
#  * uninstall: to uninstall the coverage hook
pulp_coverage_action: "install"

# Directory where the coverage report is going to be created
pulp_coverage_report_dir: "."

# Services that need to be managed in order to coverage work
pulp_coverage_services:
  - httpd
  - pulp_workers
  - pulp_celerybeat
  - pulp_resource_manager
