- name: Install required packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - mod_wsgi
    - python-crane
  notify: restart apache # for mod_wsgi

- name: Install Apache configuration file
  copy:
    src: pulp_crane.conf
    dest: /etc/httpd/conf.d/pulp_crane.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache

# NOTE: This task exists as a work-around for https://pulp.plan.io/issues/2719
# When that issue is fixed, this task should be removed.
- name: "Let Apache bind to port 5000"
  seboolean:
    name: httpd_use_openstack
    state: true
    persistent: true

- name: Install Crane configuration file
  copy:
    src: crane.conf
    dest: /etc/crane.conf
    owner: root
    group: root
    mode: 0644

- name: Open firewall port for Crane
  firewalld:
    port: "5000/tcp"
    state: enabled
    permanent: true
    immediate: true
