---
- name: Ensure Python 3 is present (RHEL)
  action: "{{ ansible_pkg_mgr }} name=python34 state=present"
  when: ansible_distribution == "RedHat"

- name: Ensure Python 3 is present (non-RHEL)
  action: "{{ ansible_pkg_mgr }} name=python3 state=present"
  when: ansible_distribution != "RedHat"

- name: Ensure Git is present
  action: "{{ ansible_pkg_mgr }} name=git state=present"
