koji-target-prefix: pulp-2.12
rsync-target-dir: 2.12/stage
rsync-tested-dir: 2.12/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: 2.12-release
    version: 2.12.0-2
# build-all.py patch required to build this release for el6 only
