koji-target-prefix: pulp-2.13
rsync-target-dir: 2.13/stage
rsync-tested-dir: 2.13/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    parent_branch: 2.13-dev
    git_branch: pulp-2.13.0-0.1.beta
    version: 2.13.0-0.2.rc
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    parent_branch: 2.13-dev
    git_branch: pulp-puppet-2.13.0-0.1.beta
    version: 2.13.0-0.2.rc
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    parent_branch: 2.13-dev
    git_branch: pulp-rpm-2.13.0-0.1.beta
    version: 2.13.0-0.2.rc
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    parent_branch: 2.4-dev
    git_branch: pulp-docker-2.4.0-0.1.beta
    version: 2.4.0-0.2.rc
  - name: crane
    git_url: git@github.com:pulp/crane.git
    parent_branch: 2.1-dev
    git_branch: python-crane-2.1.0-0.1.beta
    version: 2.1.0-0.2.rc
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    parent_branch: 1.2-dev
    git_branch: pulp-ostree-1.2.1-1.1.beta
    version: 1.2.1-1.2.rc
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    parent_branch: 2.0-dev
    git_branch: pulp-python-2.0.0-0.2.beta
    version: 2.0.0-0.3.rc
