koji-target-prefix: pulp-2.14
rsync-target-dir: 2.14/stage
rsync-tested-dir: 2.14/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    parent_branch: 2.14-dev
    git_branch: pulp-2.14.0-0.2.beta
    version: 2.14.0-0.3.rc
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    parent_branch: 2.14-dev
    git_branch: pulp-puppet-2.14.0-0.2.beta
    version: 2.14.0-0.3.rc
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    parent_branch: 2.14-dev
    git_branch: pulp-rpm-2.14.0-0.2.beta
    version: 2.14.0-0.3.rc
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    parent_branch: 3.0-dev
    git_branch: pulp-docker-3.0.0-0.2.beta
    version: 3.0.0-0.3.rc
  - name: crane
    git_url: git@github.com:pulp/crane.git
    parent_branch: 3.0-dev
    git_branch: python-crane-3.0.0-0.2.beta
    version: 3.0.0-0.3.rc
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    parent_branch: 1.3-dev
    git_branch: pulp-ostree-1.3.0-0.2.beta
    version: 1.3.0-0.3.rc
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    parent_branch: 2.0-dev
    git_branch: pulp-python-2.0.1-0.2.beta
    version: 2.0.1-0.3.rc
  - name: pulp_deb
    git_url: git@github.com:pulp/pulp_deb.git
    parent_branch: 1.5-dev
    git_branch: pulp-deb-1.5.2-0.2.beta
    versoin: 1.5.2-0.3.rc
