koji-target-prefix: pulp-2.6-testing
rsync-target-dir: 2.6/testing
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: 2.6-testing
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: 2.6-testing
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: 2.6-testing
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 1.0-testing
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: 1.0-testing
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 1.0-testing
