koji-target-prefix: pulp-2.9
rsync-target-dir: 2.9/stage
rsync-tested-dir: 2.9/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: 2.9-dev
    version: 2.9.0-0.2.alpha
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: 2.9-dev
    version: 2.9.0-0.2.alpha
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: 2.9-dev
    version: 2.9.0-0.2.alpha
# These should match 2.8-build, we're building the releases simultaneously,
# and no independent plugins have x or y bumps for 2.9. 2.8.5 will release
# before 2.9, so 2.9 should use the plugin versions released with 2.8.5
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 2.0-dev
    version: 2.0.2-0.2.beta
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: 2.0-dev
    version: 2.0.1-0.1.beta
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: 1.1-dev
    version: 1.1.2-0.1.beta
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 1.1-dev
    version: 1.1.2-0.2.beta
