# This build config only exists to build documentation for 3.0-dev.
# 3.0-dev cannot be built with the build system that uses this config.
# It will be built with the new copr-based build system.
koji-target-prefix: pulp-3.0
rsync-target-dir: 3.0/stage
rsync-tested-dir: 3.0/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: 3.0-dev
    version: 3.0.0-0.0.alpha
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: 3.0-dev
    version: 3.0.0-0.0.alpha
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: 3.0-dev
    version: 3.0.0-0.0.alpha
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 3.0-dev
    version: 3.0.0-0.0.alpha
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: 3.0-dev
    version: 3.0.0-0.0.alpha
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 3.0-dev
    version: 3.0.0-0.0.alpha
# crane isn't on the cool 3.0-dev boat
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: master
    version: 2.1.0-0.1.alpha
