koji-target-prefix: pulp-2.7
rsync-target-dir: master
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: master
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: master
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: master
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: master
  - name: pulp_deb
    git_url: git@github.com:pulp/pulp_deb.git
    git_branch: master
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: master
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: master
