---
- name: Stop services
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ pulp_coverage_services }}"

- name: Clean up previous coverage data
  file:
    path: /srv/pulp_coverage
    state: absent

- name: Create Pulp coverage directory
  file:
    mode: 1777
    path: /srv/pulp_coverage
    state: directory

- name: Clone coverage repository
  git:
    repo: https://github.com/pulp/pulp.git
    dest: pulp
    depth: 1

- name: Install coverage package
  action: "{{ ansible_pkg_mgr }} name=python-coverage state=latest"

- name: Install the coverage hook
  command: ./coverage_hook install
  args:
    chdir: pulp/playpen/coverage

- name: Start services
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ pulp_coverage_services }}"
