---
- name: Stop services
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ pulp_coverage_services }}"

- name: Generate the coverage report
  command: "./coverage_hook report {{ pulp_coverage_report_dir }}"
  args:
    chdir: pulp/playpen/coverage

- name: Remove old coverage data
  file:
    path: /srv/pulp_coverage/*
    state: absent

- name: Start services
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ pulp_coverage_services }}"
