---

- name: Install MongoDB server
  action: "{{ ansible_pkg_mgr }} name=mongodb-server state=latest"

- name: Start and enable MongoDB server service
  service: name=mongod state=started enabled=yes

- name: Setup qpid custom repo
  get_url: url=https://copr.fedoraproject.org/coprs/irina/qpid/repo/epel-6/irina-qpid-epel-6.repo dest=/etc/yum.repos.d/irina-qpid.repo
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 6

- name: Install qpid-cpp server
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - qpid-cpp-server
    - qpid-cpp-server-linearstore

- name: Start and enable qpid-cpp server service
  service: name=qpidd state=started enabled=yes

- name: Setup Pulp repository
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
  with_dict:
    pulp:
      name: Pulp Project repository
      baseurl: "https://repos.fedorapeople.org/pulp/pulp/testing/automation/{{ pulp_version }}/stage/{% if ansible_distribution == 'Fedora' %}fedora-{% endif %}$releasever/$basearch/"

      gpgcheck: 0

- name: Install Pulp Server
  action: "{{ ansible_pkg_mgr }} name=@pulp-server-qpid"
  notify:
    - Restart Apache service
    - Restart Pulp workers service
    - Restart Pulp celerybeat service
    - Restart Pulp resource manager service

- name: Check if Pulp's DB was initialized
  stat:
    path: /var/lib/pulp/db_initialized.flag
  register: db_init

- name: Initialize Pulp's DB
  shell: sudo -u apache pulp-manage-db && touch /var/lib/pulp/db_initialized.flag
  notify:
    - Restart Apache service
    - Restart Pulp workers service
    - Restart Pulp celerybeat service
    - Restart Pulp resource manager service
  when: not db_init.stat.exists

- name: Ensure Apache server is running
  service:
    name: httpd
    enabled: yes
    state: running

- name: Ensure Pulp workers are running
  service:
    name: pulp_workers
    enabled: yes
    state: running

- name: Ensure Pulp celerybeat is running
  service:
    name: pulp_celerybeat
    enabled: yes
    state: running

- name: Ensure Pulp resource manager is running
  service:
    name: pulp_resource_manager
    enabled: yes
    state: running
